version: "3.3"

services:
  server:
    container_name: spotify-seedem
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
      - ./php-ini/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    ports:
      - "8001:80"
    expose:
      - 80